clusterAlgorithm: lsst.ctrl.bps.quantum_clustering_funcs.dimension_clustering
#making changes for HSC processing
cluster:
#    visit_detector_1:
#       # pipetasks: isr,characterizeImage,calibrate,writeSourceTable,transformSourceTable
#        pipetasks: isr,characterizeImage,calibrate,writePreSourceTable,transformPreSourceTable
#        dimensions: visit,detector
#        equalDimensions: visit:exposure
    visit_step2a:
        pipetasks: consolidatePreSourceTable,consolidateVisitSummary,skyCorr
        dimensions: visit
    tract_step2b:
        pipetasks: isolatedStarAssociation,jointcal
        dimensions: tract
# global_step2c:
#       pipetasks: fgcmBuildStarsTable,fgcmFitCycle,fgcmOutputProducts
    visit_step2d:
        pipetasks: finalizeCharacterization,writeRecalibratedSourceTable,transformSourceTable,consolidateSourceTable,updateVisitSummary
        dimensions: visit
    global_step2e:
        pipetasks: makeCcdVisitTable,makeVisitTable
#    patch_coaddition:
#        pipetasks: assembleCoadd,templateGen,detection
#        dimensions: tract,patch,band
#        request_memory: 16384
#    patch_detect_deblend:
#        pipetasks: mergeDetections,deblend
#        dimensions: tract,patch
#        request_memory: 16384
#    patch_postprocess:
#        pipetasks: writeObjectTable,transformObjectTable
#        dimensions: tract,patch
#        request_memory: 16384
#    faro_step3:
#        pipetasks: PA1,PF1_design,AM1,AM2,AM3,AD1_design,AD2_design,AD3_design,AF1_design,AF2_design,AF3_design,modelPhotRepGal1,modelPhotRepGal2,mo#delPhotRepGal3,modelPhotRepGal4,modelPhotRepStar1,modelPhotRepStar2,modelPhotRepStar3,modelPhotRepStar4,psfPhotRepStar1,psfPhotRepStar2,psfPhotRepStar3,psfPhotRepStar4
#        dimensions: tract,band
#        request_memory: 4096
#    diffim_forced_phot:
#        pipetasks: getTemplate,imageDifference,transformDiaSourceCat,forcedPhotCcd,forcedPhotDiffim,writeForcedSourceTable
#        dimensions: visit,detector
#        request_memory: 4096
#    diffim:
#        pipetasks: getTemplate,imageDifference,transformDiaSourceCat
#        dimensions: visit,detector
#        #dimensions: visit,detector,skymap
#    association:
#        pipetasks: drpAssociation,drpDiaCalculation
#        dimensions: tract,patch
#    forced_phot_detector:
        # All of these tasks _can_ be run together, but forcedPhotCcd (and to
        # a lesser extent, forcedPhotDiffim and writeForcedSourceTable) may be
        # unblocked much earlier; operators may want to split this cluster up
        # on that basis.
#        pipetasks: forcedPhotCcd,forcedPhotDiffim,forcedPhotDiffOnDiaObjects,forcedPhotCcdOnDiaObjects,writeForcedSourceTable
#        dimensions: tract,visit,detector
#    forced_phot_step5:
#        pipetasks: forcedPhotDiffOnDiaObjects,forcedPhotCcdOnDiaObjects,writeForcedSourceOnDiaObjectTable
#        dimensions: visit,detector
#        dimensions: tract,visit,detector
#    property_maps:
#        pipetasks: healSparsePropertyMaps
#        dimensions: tract,band
#    recalibrate_step6:
#        pipetasks: writeRecalibrateSourceTable,transformRecalibratedSourceTable
#        dimensions: visit,detector
