includeConfigs:
- ${CTRL_BPS_PANDA_DIR}/config/bps_usdf.yaml
- ${CM_PROD_DIR}/src/lsst/cm/prod/configs/PDR2/requestMemory.yaml
- ${CM_PROD_DIR}/src/lsst/cm/prod/configs/PDR2/clustering_step2d_both.yaml
numberOfRetries: 3

fileDistributionEndPoint: "file:///sdf/data/rubin/panda_jobs/panda_cache/{operator}/panda_cache_box/{payloadFolder}/{uniqProcName}/"

custom_lsst_setup: ""

# turn off the -o option in pipetask commands
pipetaskOutput: ""

executionButler:
  requestMemory: 64000
  queue: "SLAC_Rubin_Merge"
  # turn off chaining in the execution butler because
  # no output collection
  command2: ""
  command3: ""
